id = "blackula"
name = "Blackula"
version = "0.1.0"
schema_version = 1
authors = ["Jacob Coffee <jacob@z7x.org>"]
description = "A superdark Dracula theme for Zed"
repository = "https://github.com/JacobCoffee/blackula"
